version: "3"
services:
 frontend:
  build: ./front
  ports:
   - 80:80
 backend:
  build: ./back
  ports:
   - 3000:3000
  environment:
   MongoDB: mongodb://database/
  command: ./docker-entrypoint.sh
 database:
  image: mongo:6.0.4-jammy
  ports:
   - 27017:27017
